# Generated by Django 4.0.6 on 2022-07-27 05:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaryDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diary_name', models.CharField(default='set', max_length=16, unique=True)),
                ('first_name', models.CharField(default='first', max_length=16)),
                ('last_name', models.CharField(default='last', max_length=16)),
                ('gender', models.CharField(default='M', max_length=1)),
                ('age', models.SmallIntegerField(default=0)),
                ('weight', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Diet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(default='food', max_length=16)),
                ('calories', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=5, null=True)),
                ('fat', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=5, null=True)),
                ('carbohydrates', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=5, null=True)),
                ('protein', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=5, null=True)),
                ('fiber', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=5, null=True)),
                ('sugar', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=5, null=True)),
                ('sodium', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.diarydetails')),
            ],
        ),
    ]
