# Generated by Django 4.0.6 on 2022-08-01 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diet',
            old_name='carbohydrates',
            new_name='Carbohydrate',
        ),
        migrations.RenameField(
            model_name='diet',
            old_name='calories',
            new_name='Energy',
        ),
        migrations.RenameField(
            model_name='diet',
            old_name='fat',
            new_name='Fat',
        ),
        migrations.RenameField(
            model_name='diet',
            old_name='fiber',
            new_name='Fiber',
        ),
        migrations.RenameField(
            model_name='diet',
            old_name='protein',
            new_name='Protein',
        ),
        migrations.RenameField(
            model_name='diet',
            old_name='sodium',
            new_name='Sodium',
        ),
        migrations.RenameField(
            model_name='diet',
            old_name='sugar',
            new_name='Sugars',
        ),
    ]
