# Generated by Django 4.0.6 on 2022-08-02 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_carbohydrates_diet_carbohydrate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diet',
            name='Grams',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=8, null=True),
        ),
    ]
